# Generated by Django 5.2.7 on 2025-11-05 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeverUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activation_key', models.CharField(blank=True, max_length=255)),
                ('installed_on_time', models.IntegerField(default=0)),
                ('last_viewed_on_time', models.IntegerField(default=0)),
                ('last_session_on_time', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=143)),
            ],
            options={
                'db_table': 'fever_users',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfg', models.TextField()),
                ('prefs', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fever_config',
            },
        ),
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('url_checksum', models.IntegerField(unique=True)),
                ('last_cached_on_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fever_favicons',
                'indexes': [models.Index(fields=['last_cached_on_time'], name='fever_favic_last_ca_12cfd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('url_checksum', models.IntegerField(unique=True)),
                ('site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('requires_auth', models.BooleanField(default=False)),
                ('auth', models.CharField(blank=True, max_length=255, null=True)),
                ('is_spark', models.BooleanField(default=False)),
                ('prevents_hotlinking', models.BooleanField(default=False)),
                ('item_excerpts', models.SmallIntegerField(default=-1)),
                ('item_allows', models.SmallIntegerField(default=-1)),
                ('unread_counts', models.SmallIntegerField(default=-1)),
                ('sort_order', models.SmallIntegerField(default=-1)),
                ('last_refreshed_on_time', models.IntegerField(default=0)),
                ('last_updated_on_time', models.IntegerField(default=0)),
                ('last_added_on_time', models.IntegerField(default=0)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.favicon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fever_feeds',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_excerpts', models.SmallIntegerField(default=-1)),
                ('item_allows', models.SmallIntegerField(default=-1)),
                ('unread_counts', models.SmallIntegerField(default=-1)),
                ('sort_order', models.SmallIntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fever_groups',
            },
        ),
        migrations.CreateModel(
            name='FeedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feed')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'db_table': 'fever_feeds_groups',
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='groups',
            field=models.ManyToManyField(related_name='feeds', through='api.FeedGroup', to='api.group'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('url_checksum', models.IntegerField()),
                ('read_on_time', models.IntegerField(default=0)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_on_time', models.IntegerField()),
                ('added_on_time', models.IntegerField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.feed')),
            ],
            options={
                'db_table': 'fever_items',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('is_item', models.BooleanField(default=False)),
                ('is_local', models.BooleanField(default=False)),
                ('is_first', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('url_checksum', models.IntegerField()),
                ('title_url_checksum', models.IntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('created_on_time', models.IntegerField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.feed')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_links', to='api.item')),
            ],
            options={
                'db_table': 'fever_links',
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['title'], name='fever_group_title_29592d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedgroup',
            index=models.Index(fields=['feed', 'group'], name='fever_feeds_feed_id_047b6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedgroup',
            unique_together={('feed', 'group')},
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['favicon'], name='fever_feeds_favicon_d3ab96_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['title'], name='fever_feeds_title_92af58_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['domain'], name='fever_feeds_domain_c5f78b_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['is_spark'], name='fever_feeds_is_spar_471e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['last_refreshed_on_time'], name='fever_feeds_last_re_d74ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['last_updated_on_time'], name='fever_feeds_last_up_5bd53e_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['last_added_on_time'], name='fever_feeds_last_ad_e21d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['feed'], name='fever_items_feed_id_129095_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['feed', 'uid'], name='fever_items_feed_id_51e08c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['title'], name='fever_items_title_2bd53f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['url_checksum'], name='fever_items_url_che_91d9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['read_on_time'], name='fever_items_read_on_7fb771_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_saved'], name='fever_items_is_save_777046_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_on_time'], name='fever_items_created_267aec_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['added_on_time'], name='fever_items_added_o_242b10_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['feed'], name='fever_links_feed_id_6deb18_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['item'], name='fever_links_item_id_f1264a_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['created_on_time'], name='fever_links_created_a237ad_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['weight'], name='fever_links_weight_80d858_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['url_checksum'], name='fever_links_url_che_20b3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['title_url_checksum'], name='fever_links_title_u_1a62d0_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['is_blacklisted'], name='fever_links_is_blac_4b267c_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['is_item'], name='fever_links_is_item_39560f_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['is_local'], name='fever_links_is_loca_7fd7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['is_first'], name='fever_links_is_firs_e52b55_idx'),
        ),
    ]
