# Generated by Django 5.2.7 on 2025-11-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feveruser',
            name='fever_api_key',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
