# Generated by Django 6.0 on 2025-12-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feveruser_groups_feveruser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='last_cached_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='url_checksum',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_added_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_refreshed_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_updated_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url_checksum',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='feveruser',
            name='installed_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feveruser',
            name='last_session_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feveruser',
            name='last_viewed_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_on_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='read_on_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_checksum',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_on_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='title_url_checksum',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='url_checksum',
            field=models.BigIntegerField(),
        ),
    ]
