# Generated by Django 5.2.7 on 2025-12-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_favicon_last_cached_on_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='user_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url_checksum',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
